-- supabase/migrations/20241114000002_create_in_app_messages.sql
CREATE TABLE public.in_app_messages (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    title text not null,
    message text not null
);

ALTER TABLE public.in_app_messages ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.in_app_messages
    OWNER to postgres;

ALTER PUBLICATION supabase_realtime ADD TABLE public.in_app_messages;

-- This is the missing piece: A policy to allow authenticated users to read messages.
CREATE POLICY "Allow authenticated users to read messages"
    ON public.in_app_messages
    FOR SELECT
    TO authenticated
    USING (true);
