-- Create the in_app_messages table
CREATE TABLE IF NOT EXISTS public.in_app_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Secure the table with Row-Level Security
ALTER TABLE public.in_app_messages ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read messages
CREATE POLICY "Allow authenticated read access" ON public.in_app_messages
    FOR SELECT
    TO authenticated
    USING (true);

-- Set up the publication for real-time updates
CREATE PUBLICATION supabase_realtime FOR TABLE public.in_app_messages;
